### ISSUE TITLE
iitmdiss.cls file

### ISSUE THREAD

**Issue by harimaruthachalam** [j-jith/iitm-thesis#1]
Hi,

This is a syntax issue in the mentioned file, line number 355. There is an excess curly brace. Please have a look.

\def\committee{\chapter*{\centerline{GENERAL TEST COMITTEE}}}

Thanks,
Hari.

**Comment by j-jith** [comment]
Thanks for pointing this out. This was part of the original class file. I wonder why nobody has noticed this till now.

I am not in a position to edit this right now. If you could open a pull request, I will merge it.

**Comment by harimaruthachalam** [comment]
HI,

I couldn't push the changes as I don't have permissions.

**Comment by j-jith** [comment]
You can't push the changes directly. Please fork this repository, push changes to that and open a pull request here.

**Comment by harimaruthachalam** [comment]
Created a pull request. Please merge it.

**Comment by j-jith** [comment]
Thanks. I have merged it.
